### ISSUE TITLE
Support en_GB 

### ISSUE THREAD

**Issue by bookercodes** [andischerer/atom-keyboard-localization#101]
When using [vim-mode](https://github.com/atom/vim-mode) or [vim-surround](https://github.com/tpope/vim-surround) with an [en_GB](https://en.wikipedia.org/wiki/British_and_American_keyboards#/media/File:KB_United_Kingdom.svg) keyboard, no motions that include the following character work: `'`, `"`, `~`.

I encountered this problem a while ago in [this issue](https://github.com/atom/vim-mode/issues/853) which may provide additional context if needed.

**Comment by bluekeys** [comment]
I'm also experiencing this. I can add any additional details as required. I would like to contribute a standard en_GB keymap, but will need hand-holding, I just can't achieve success using the keymap generator.

**Comment by bookercodes** [comment]
@bluekeys You could try using the keymap I contributed in #102. 

If you encounter any trouble, let me know and I'll be glad to help :smile:

**Comment by sandman21dan** [comment]
Bump

**Comment by bookercodes** [comment]
@sandman21dan I made a pull request for this: https://github.com/andischerer/atom-keyboard-localization/pull/102

**Comment by andischerer** [comment]
Will be :ship: in the next release

**Comment by bookercodes** [comment]
Thank you, @andischerer!
