### ISSUE TITLE
sporadic wrong mappings

### ISSUE THREAD

**Issue by luxigo** [andischerer/atom-keyboard-localization#108]
Hi !

Thanks everybody for this extension.

Sounds crazy but without it Atom is useless for so many people, that would immediately switch to another editor.. :8ball: 

Anyway sometimes (or twice daily :-1: ) I have wrong mappings for characters like | and [, or was it { ?... 

Maybe after switching to another application or resuming from sleep/hibernation.

(Using fr_CH keyboard with latest stable Debian and Atom version, currently 1.5.3)

When it happens, I must select the "Packages -> Keyboard Localization -> Open Keymap Generator" menu option.

Here I must type the character in the input labelled "Capture Key-Events from input and create Key-Mappings".

Then I must go back to the editor tab without closing the Keymap Generator tab, and the character is mapped properly again. :+1: 

Hope since a long time that it can be fixed very soon

**Comment by luxigo** [comment]
I will try to add generated mappings to fr_CH.json when it happens again

**Comment by jpmn** [comment]
I experienced the samething (locale fr_CA) with character { while expecting \ with the mapping altgr + ~ (the key at the left of number 1). Latest release of the package as per Atom: 1.4.15

I opened the Keymap-Generator and the mapping was temporarly fixed until the tab is closed.

**Comment by luxigo** [comment]
Adding the mapping to fr_CH.json solved the recurrency problem ... (until the next Keymap-Generator update :-) )

**Comment by jpmn** [comment]
I still experience the problem (same version as before with latest Atom).

When I press `ctrl + left-alt + ~`, it prints the expected character `\`. But it should be the same using `right-alt + ~` which prints `{`. I don't think I had this behavior before.

If the Keymap-Generator is opened, the problem does not occur and everything is normal as usual.

This is the captured mapping when tested in the Keymap-Generator (which prints `\` as it should from `altgr + ~`):

```
{
    "222": {
        "alted": 92
    }
}
```

**Comment by jpmn** [comment]
I think this is the faulty commit: https://github.com/andischerer/atom-keyboard-localization/commit/414576c779773fc92a3c51ba3de57e304e7f2459

**Comment by doktordirk** [comment]
Tx for the plugin!

might be related: virtual AltGr
using de_DE i sometimes get a virtual AltGr added. so e beomes €, m to µ and 3 to ³.... haven't seen much of a pattern yet (though just now it reverted to normal after tabbing out an in again).

**Comment by KrisMoody** [comment]
Thanks for a great plugin!

I seem to have the same issue as doktordirk with a Swedish keyboard and it seems to be random. Issues with pipes and spaces too. For me, it just started when I updated Atom to the latest release (I guess. Might have been some plugin updates too).

**Comment by doktordirk** [comment]
fyi: it's constistent now: starts with any AltGr sign and stops when tabbing out/in

**Comment by KrisMoody** [comment]
Thanks man! Seems to solve it for me too!

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
