### ISSUE TITLE
AltGr key stays as down with current atom git version.

### ISSUE THREAD

**Issue by paradoxxxzero** [andischerer/atom-keyboard-localization#110]
On linux (atom/atom@663d9b234cdd125e644af1716eadaae62f496b6a), this event https://github.com/andischerer/atom-keyboard-localization/blob/master/lib/modifier-state-handler.coffee#L168 doesn't fire anymore so altgr always stay pushed.

**Comment by zokker13** [comment]
_confirm_ This renders the plugin useless.

**Comment by demhydraz** [comment]
Can confirm on 1.7.0-beta0.

**Comment by hebbet** [comment]
@demhydraz maybe you do a PR on atom

**Comment by demhydraz** [comment]
I think the proper fix would be adding a `keyboard-localization:altgr-up` command and binding that to `^altgr` by default on >1.7, and keeping the old behaviour (DOM event handler) on <1.7.

**Comment by rapus95** [comment]
a rather primitive workaround (not fix and kinda dumb) is to manually "unlock" AltGr by doing these 4 steps pretty slow:
hit ctrl (left)
hit alt (left)
leave alt (left)
leave ctrl (left)

It at least worked on windows though not practical and kinda hackish... sadly i don't understand enough coffeescript to change anything effectively and the owner doesn't seem to be around these days

**Comment by andischerer** [comment]
Sorry for the late response. I think next week i'll have some time for investigating. Until then i suggest using atom stable.

**Comment by andischerer** [comment]
Looks like there is no need for an own keyup event handler implementation anymore. 
Since atom v1.7 keyup events flow through the same keydownhandler core function. 
Should be an easy fix within the package.

**Comment by demhydraz** [comment]
:+1: Thanks! All works now ([modified pt_BR](https://github.com/demhydraz/til/blob/master/atom/keylayout.json)) and 1.7.0-beta2.

**Comment by rapus95** [comment]
Sadly doesn't work for me at the moment, means AltGr still remains pressed.
Well as far as i can see the updated version (1.4.16) doesn't contain the changed source, thus asking when it will be part of the official release? I tried Atom 1.7.0-beta0 and beta4.
(Or may it be that there's any error with the version handling in Atom?)

**Comment by andischerer** [comment]
I havent published the fix for Altgr down yet. The fix is at the moment in a [branch](https://github.com/andischerer/atom-keyboard-localization/tree/fix-keyup-listener) and i've have to do a little testing before i merged and published it.
I'll leave you a note when its ready.

**Comment by demhydraz** [comment]
@rapus95 Meanwhile, you can get the changes (as I did) by doing `git clone git@github.com:andischerer/atom-keyboard-localization.git keyboard-localization -b fix-keyup-listener` in `~/.atom/packages`

**Comment by andischerer** [comment]
should be fixed in v1.4.17

**Comment by rapus95** [comment]
Atom 1.7.0-beta4 only allows me to install 1.4.16 while showing the following message:
"Version 1.4.16 is not the latest version available for this package, but it's the latest that is compatible with your version of Atom."

**Comment by andischerer** [comment]
@rapus95 should be working now. I fixed the semver check for beta channel support.
