### ISSUE TITLE
Difference between OSX and Windows

### ISSUE THREAD

**Issue by hmps** [andischerer/atom-keyboard-localization#112]
Swedish keyboards on OSX has the "|" character (keyCode 124) mapped to `⌥ + 7`. See keyboard layouts below for verification (There are two alternate layouts, Pro and Standard, but both has the same | mapping).
## Swedish

![monosnap 2016-03-14 15-43-24](https://cloud.githubusercontent.com/assets/1231909/13748365/d1687758-e9fc-11e5-9a61-aeff3c33e16b.png)
## Swedish Pro

![monosnap 2016-03-14 15-44-13](https://cloud.githubusercontent.com/assets/1231909/13748370/d9553230-e9fc-11e5-8e07-7d356100a1ff.png)

Swedish keyboards on Windows are mapped as the current layout in this repo. I'm happy to PR, but would like to know if it's acceptable to create a second set of Swedish mappings, with the OSX standards?

**Comment by andischerer** [comment]
In my experience osx keymappings should work out of the box without this package. If not i think its ok to create a second set of mappings for osx.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
