### ISSUE TITLE
de_DE shortcuts aren't the same on Windows and Linux

### ISSUE THREAD

**Issue by lukasmalkmus** [andischerer/atom-keyboard-localization#114]
Hi,
why is it, that I can use _Ctrl+Alt+q_ to write an **@** or _Ctrl+Alt+8_, _Ctrl+Alt+9_ to write **[** and **]** on my Windows 10 machine but not on my Linux machine? Both run Atom 1.5.4 with latest "atom-keyboard-localization" package installed. On my Linux machine I need to use _AltGr+q/8/9_ and these shortcuts also work on my Windows 10 machine. Both installations **are not** customized with custom keymaps or init-scripts.

So I suspect it's either an package issue or it depends un the OS. Any comments?

**Comment by hmps** [comment]
I have a similar issue with different key mappings in different OS, see https://github.com/andischerer/atom-keyboard-localization/issues/112

**Comment by andischerer** [comment]
This is an OS keydown handling issue. 
Linux has a more proper AltGr keyhandling than Windows. Windows fires two keydown events(alt and ctrl) on AltGr down and linux fires only one event with a specific charcode for AltGr.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
