### ISSUE TITLE
Atom does not register altgr unpress

### ISSUE THREAD

**Issue by doivosevic** [andischerer/atom-keyboard-localization#115]
I'm using slovenian keyboard setup.
When I use altgr key to write, i.e. altgr+f = '[' after I unpress altgr key and lets say want to write 'v' it behaves as if I did not unpress altgr and writes '@' instead.
This happens until I alt+tab and return to atom. Then altgr is unpressed until I press it again.
I can write 'normally' if after I use altgr I doubleclick win key to unfocus+focus atom.

Windows 10
Atom 1.7 beta0
keyboard-localization 1.4.15

**Comment by erikusaj** [comment]
**Not repro**

Windows 10
Atom 6.0
keyboard-localizytion 1.4.11

Windows 10
Atom 6.0
keyboard-localizytion 1.4.15

If it's not a hardware issue and you are still able to reproduce provide more specific steps:
1. Use Slovenian keyboard on Windows as default
2. Launch Atom  
3. type AltGr+F to output "["
4. press AltGr then unpress AltGr
5. key V
Observed:  output as expected "[v" (due code auto-completion: "[v]" )

**Comment by hebbet** [comment]
there is not yet an atom 6.0

**Comment by rapus95** [comment]
yeah same for me with the german layout. Works flawlessly in Atom 1.6.0 but fails to release AltGr in Atom 1.7beta0
might we can merge this with https://github.com/andischerer/atom-keyboard-localization/issues/110 as being somewhat the same problem? (being related to atom >1.6)

**Comment by andischerer** [comment]
Dupe, subscribe here #110
