### ISSUE TITLE
Bug with selfclosing html tags

### ISSUE THREAD

**Issue by fingust** [andischerer/atom-keyboard-localization#118]
Hi there, i would like to report a bug i've recently ran into... Whenever i use your plugin which is essential if i even want to normally use this editor, while coding html with self closing tags enabled, this plugin makes it self close 4 times.

Which means that i type:
<h1
And when i close it with > i get that:

<h1></h1></h1></h1></h1>

//this is straight copy paste from editor, i can even make a video if you don't understand me, cause my english kinda sux :D

Thank you, keep up great work.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
