### ISSUE TITLE
The package no longer works on Atom 1.7 beta0 with hu_HU keyboard

### ISSUE THREAD

**Issue by LZL0** [andischerer/atom-keyboard-localization#119]
The package no longer works on Atom 1.7 beta0 (Windows) with hu_HU keyboard.
Most noticeably if I hit Ctrl + S (Save) it will write "đ", which is Alt Gr+S on the keyboard.
The situation is same with Ctrl + A for instance, it would type "ä" (Alt Gr + S) instead of Ctrl + A.
In the past when I hit Ctrl + S (Save) it wrote sometimes unpredictably and randomly a "đ" sign.

P.s.: I have been using this package, and I must say it is awesome! So keep up the great work!  :+1: :)

**Comment by andischerer** [comment]
Probably dupe of #110

**Comment by LZL0** [comment]
Most likely

**Comment by andischerer** [comment]
should be fixed in v1.4.17
