### ISSUE TITLE
Link to Spanish Latin layout is broken

### ISSUE THREAD

**Issue by merlyn333** [andischerer/atom-keyboard-localization#120]
Link to Spanish Latin layout is broken.

**Comment by Davecas** [comment]
It must be for Spanish from Spain too cause characters typed using Alt don't correspond to the character in the key.
I already opened a new issue thread for that.

**Comment by andischerer** [comment]
See #121. Is this still an issue by using v1.4.17 of this package ?

**Comment by Davecas** [comment]
Yes, I have 1.4.18 and what I said in my last post is happening to me. Using Atom 1.7.13 which seems to be the latest version.
Using spanish from spain keyboard, in case it is different from spanish latin.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
