### ISSUE TITLE
I can't type Alt+num characters properly like #

### ISSUE THREAD

**Issue by Davecas** [andischerer/atom-keyboard-localization#121]
Hello.
I installed this package cause for some reason Atom has issues for non US keyboards or something, and I couldn't type the ] character.
But after installing this package some characters in my keyboard work weirdly like when I want o type a # or some other Alt+number for example the # it types a super 3, like a power 3 small number.
I tried disabling the package but I cant type the ] again and I can type @#~€¬ etc again with no problems.
After trying again while writing this, it seems like (almost) every character that is written the Alt key is being problematic to me and writes other things instead.
My keyboard is es_ES.
For example I tried writing a ] with the package activated and will write ~ etc.
I hope I explained my self clearly enough :-)

**Comment by ManzDev** [comment]
Same problem here.

**Comment by andischerer** [comment]
Are you using atom > 1.7. If so this could be related to #110.
I fix that issue in the latest package version 1.4.17.

**Comment by ManzDev** [comment]
Correct, fixed! Thanks

**Comment by Davecas** [comment]
I still have an issue. Not sure if spanish latin keyboard is the same as spanish from spain.
But I notices I have to press left Ctrl+Alt (not altgr) to make those symbols work as if I used Altgr.
