### ISSUE TITLE
Problems with curly brackets on de_CH with OSX

### ISSUE THREAD

**Issue by Smeyke** [andischerer/atom-keyboard-localization#126]
Hi Andi

I cant fix my problem i face right now with curly brackets on the atom editor.

If i select your de_CH keymap  some stuff works, but not everything i need to work.
Here i tried to show you the problem i have:

with the de_CH
alto g @
alt 2 @
alt 3 #
shift 8/9 ()
alt 8/9 ¢ ]

without:

alt g nothing
alt 2 “”
shift 8/9 ()
alt 8/9 {}

At this moment i have to copy and paste the curly brackets everytime if i work with JS or regular CSS.

How can i fix this problem? Thanks for your time.

**Comment by bernhardw** [comment]
I was having the same problem and instead just remapped the `@` character without using this plugin.
You can add this your keymap.cson:

```
'atom-workspace':
    'alt-g': 'native!'
```
