### ISSUE TITLE
Randomly writes unexpected characters

### ISSUE THREAD

**Issue by Torniojaws** [andischerer/atom-keyboard-localization#127]
When using "fi_FI", I randomly get all kinds of gibberish characters, and after a while it continues to work again. This happens at least once an hour.

**Steps:**
Atom 1.7.0
keyboard-localization v1.4.16 and also v1.4.18

Start to write some code for a while.

Sometimes when you press:
e - you will get € instead
0 (zero above alphabets) - you will get }
5 - you will get € instead
. (period) - nothing happens and the period character does not appear

It is as if Alt Gr is "stuck". This only happens in Atom with keyboard-localization. When I disable keyboard-localization, the strange characters never happen.

**Comment by cladewig** [comment]
Same Issue: [https://github.com/andischerer/atom-keyboard-localization/issues/125](https://github.com/andischerer/atom-keyboard-localization/issues/125)

**Comment by ylorant** [comment]
Having the same issue here, with fr_FR layout.

**Comment by Tzky** [comment]
Same with de_DE localization:
trying to type `@media` results in `@µ€dia`, but only sometimes... It looks like using AltGr sometimes triggers the bug.

I'm currently using 1.4.18 and Atom 1.7.3

**Comment by SnSimon** [comment]
Maybe it is a (undocumented?) feature. 

You can switch this special characters mode on by pressing **alt gr** and switch it off by pressing **alt gr** and **alt** at the same time.

I just found that out by trying. But I think I can get used to that feature...

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
