### ISSUE TITLE
Having to add "shift" modifier to bindings in other atom packages when this plugin is enabled

### ISSUE THREAD

**Issue by protron** [andischerer/atom-keyboard-localization#129]
Seems like _atom-keyboard-localization_ is requiring changes to the way you bind shortcuts involving the <kbd>shift</kbd> key.

I discover this trying the package _last-cursor-position_ which has a <kbd>alt</kbd>-<kbd>_</kbd> binding. In the **es_LA** keyboard that I'm using the <kbd>_</kbd> is made with <kbd>shift</kbd>-<kbd>-</kbd>). The problem is when I have the _atom-keyboard-localization_ extension enabled, as the binding as it comes installed by the _last-cursor-position_ package doesn't work. And I can either disable _atom-keyboard-localization_ or add <kbd>shift</kbd> to my _keymap.cson_ for it to work again.

So keymaps defined as:

```
'alt-_': 'last-cursor-position:next'
```

which work (when _atom-keyboard-localization_ is disabled), has to be translated into:

```
'alt-shift-_': 'last-cursor-position:next'
```

when _atom-keyboard-localization_ is enabled.

Can this be fixed in here so other packages don't fail due to this package?

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
