### ISSUE TITLE
'altgr-{' does not trigger keybinding

### ISSUE THREAD

**Issue by PaulEcoffet** [andischerer/atom-keyboard-localization#130]
I want that when I type a `{` character, a specific command is triggered from latextools. According to the keybinding resolver, with my fr_FR-bepo layout, it triggers a `altgr-{` keypress. Therefore, I have written this in my keymap.cson:

``` cson
'atom-text-editor[data-grammar~=\'latex\']':
  'altgr-{': 'latextools:ref-cite-keypress',
```

But when I type a `{`, the command from latextools is not triggerred, even though I see the event `altgr-{` in the keybinding resolver.

Is it a bug, should another event  be used to trigger the command when I type a `{`?

Thank you for your help

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
