### ISSUE TITLE
Alt+8 / Alt+9 ISO keyboard

### ISSUE THREAD

**Issue by bergstar** [andischerer/atom-keyboard-localization#131]
Installed package in latest atom. 

Added following lines to keymap.cson

```
'body':
   'alt-7': 'native!' # 
   'alt-8': 'native!' #
   'alt-9': 'native!' #
   'alt-0': 'native!' #
```

Verified that they are disabled in settings and double checked nb_NO.json file

```
    "56": {
        "shifted": 40,
        "alted": 91
    },
    "57": {
        "shifted": 41,
        "alted": 93
    },
```

But I still can't get 

```
Alt+8 to [
Alt+9 to ]
```

AltGr+8 and AltGr+9 works as before. Same goes for Alt+7 { and Alt+0 to }

Would greatly appreciate any help / tips.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
