### ISSUE TITLE
Don't see an option in setting menu to set keyboard

### ISSUE THREAD

**Issue by jumbosushi** [andischerer/atom-keyboard-localization#132]
Under usage, it is said that "Inside Atom's packages management, click Settings, and in the freshly opened panel, either choose an existing Keyboard Layout from the list, or pick a keymap file from the filepicker."

I downloaded the package, but do not see any option under Setting that allows me to set the key board :(

**Comment by andischerer** [comment]
Try to restart Atom and check again.

**Comment by jumbosushi** [comment]
Hmm I tried that but it didn't work.
Am I supposed to be seeing something new under Core Settings or Editor Settings?

**Comment by andischerer** [comment]
![installtheme](https://cloud.githubusercontent.com/assets/930604/15704807/8bb861fe-27ec-11e6-920d-48cc114ec021.gif)

**Comment by jumbosushi** [comment]
Thank you :tada:
