### ISSUE TITLE
Incorrect key in et_EE map

### ISSUE THREAD

**Issue by ervinoro** [andischerer/atom-keyboard-localization#137]
https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/KB_Estonian.svg/900px-KB_Estonian.svg.png

The bottom left key is <>|, not <>-.
So et_EE.json should contain 
`{
    "220": {
        "alted": 124
    }
}`

(currently maps 220 alted to 189 instead)

**Comment by ervinoro** [comment]
Also, alt+Ä is ^, not ˇ, so 
`{ "222": { "alted": 94 } }`
?

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
