### ISSUE TITLE
es_LA: backtick behaviour

### ISSUE THREAD

**Issue by diegonc** [andischerer/atom-keyboard-localization#138]
There is a strange behaviour when using the Spanish Latin America layout. Whenever a backtick ( `  ) is typed, two of them are inserted and the next letter you type is placed after the second backtick even if the cursor is between them.

Note that backtick is a dead key, so it must be pressed twice to insert one standalone backtick character (in contrast to a diacritic like à). Maybe that's why atom gets confused. Though, I can't explain why the next typed letter is misplaced.

![backtick](https://cloud.githubusercontent.com/assets/261458/17386651/1e350b1a-59c3-11e6-83af-e1f3b26d7d73.gif)

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
