### ISSUE TITLE
sv_SE layout does not support caret

### ISSUE THREAD

**Issue by MichaelBergquistSuarez** [andischerer/atom-keyboard-localization#140]
The caret character `^` does not seem to work, making my vim-mode sad. I'm using a Swedish wireless Mac keyboard.

If it's any help, while procuding a caret, the Keymap-Generator gives me:
Identifier: U+00E5
Code: 229
Char: å
Modifier: shift

Unfortunately the generator does not produce any JSON either

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
