### ISSUE TITLE
Lots of pt_BR issues

### ISSUE THREAD

**Issue by mauricioszabo** [andischerer/atom-keyboard-localization#141]
Exactly how this package works? I've installed it, together with vim-mode-plus, and nothing is working.

For instance, in my keyboard, `:` is recognized as `?` in Atom. So, I've mapped `?` as "ex-mode:open", then I've discovered this package. So, I've re-mapped `:` as "ex-mode:open", but it didn't work.

It didn't work, either, for `ctrl+]` (Atom keeps understanding it as `ctrl+\`, nor as any other combination. How do I make it work?

**Comment by mauricioszabo** [comment]
Just a strange thing I've detected, when I try to build a keymap, my `;` and my `?` keybindings overwrite each other. Here, a GIF showing this behavior:

![example](https://cloud.githubusercontent.com/assets/138037/17671471/870e6fe0-62ed-11e6-95fc-2a0cc56ca610.gif)

As you can see, I press `;` and Atom detects as `/`. If I press `;` again, Atom detects it as `;` (the correct behavior).
But, when I press `/`, Atom detects as `;`. If I press `/` again, it detects as `/` (the correct behavior), but now `;` is wrong again...

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
