### ISSUE TITLE
AltGr + - should write *

### ISSUE THREAD

**Issue by Sebosek** [andischerer/atom-keyboard-localization#143]
Windows 10, Atom 1.9.9, keyboard-localization 1.4.18, I'm using czech keyboard layout, and altgr+- should write *, but it writes simple -.
But when I'm trying to specify shortcut in Keymap-Generator, nothing happend in Keymap-Generator, instead "flex-grow" is applied to main Atom canvas...

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
