### ISSUE TITLE
Add nl_BE as an alias for French azerty

### ISSUE THREAD

**Issue by BramVanroy** [andischerer/atom-keyboard-localization#144]
As commented here: https://github.com/atom/atom-keymap/issues/37#issuecomment-238387162

> I am using the fr_BE layout. Note that an alias nl_BE would be nice. Quick info: one half of Belgium speaks French, the other Dutch - but we all (mostly) use an azerty (French) keyboard. (Oh, and a couple of folks in the East speak German. I am not sure which layout they'd use!)

In other words, it might be useful for the Dutch speaking part to have a Dutch (nl) alias for their keyboard. `fr_BE = nl_BE`

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
