### ISSUE TITLE
fr_BE double tilde

### ISSUE THREAD

**Issue by BramVanroy** [andischerer/atom-keyboard-localization#145]
When typing a tilde with this keyboard and following it by any key results in two tilde characters.

Default behaviour would be:
- `Alt Gr` + `=` (nothing happens)
- Type any character
- Where applicable the tilde transform the input character into a diacritic. If not, just type a tilde

So you always need two key presses to get the regular tilde.

Current behaviour:
- `Alt Gr` + `=` results in a regular tilde
- Type any character
- Where applicable the tilde transform the input character into a diacritic. If not, just type a tilde

So you _always_ get two tildes.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
