### ISSUE TITLE
Multi combo bindings

### ISSUE THREAD

**Issue by flekmatik** [andischerer/atom-keyboard-localization#15]
Nice idea and great work with this package!!

I am trying to set up czech qwerty layout and I run into problem. To write characters from US layout we can use modifier AltGr e.g. to write "[" i can press AlgGr+[ ... this works flawlessly. But to write "{" i have to press AltGr+Shift+[ ... I noticed that your module doesn't support multi-combo bindings ("altshifted" etc) yet.

Do you plan to support this?

**Comment by andischerer** [comment]
Yes, you are right, multi-modifier bindings are currently not supportet. In future i plan to implement this and therefore i have to rething the keymapper and keymaps.
Due to my limited time at the moment i can't really promise when this feature will land in the package.

**Comment by andischerer** [comment]
I'm currently implementing multi combo bindings. Are there any other AltGr-Shift-Modifier bindings on a czech layout except AltGr+Shift+[

**Comment by flekmatik** [comment]
I know just {, }, ~ and |

**Comment by andischerer** [comment]
You mind sharing your czech kemap file ?

**Comment by flekmatik** [comment]
Atom was not usable for me without braces so I switched to vim. I can generate keymap file when multi-combo bindings will be supported.

**Comment by andischerer** [comment]
Multi-Combo bindings are now available in v1.3.0 ;-)

The keybinding generator doesent support the AltGr+Shift bindings atm. You have to insert them by hand in your json file.
You could look at https://github.com/andischerer/atom-keyboard-localization/blob/master/lib/keymaps/pl_PL.json for an working example.
