### ISSUE TITLE
RAlt+Shift for uppercase Polish national letters.

### ISSUE THREAD

**Issue by ghost** [andischerer/atom-keyboard-localization#17]
I have Windows 10 (build 1041) and Atom 0.189
I create json for "Polish (Programmers)" default keyboard layout on Windows in Poland. This contain only [Right ALT] + [e], [o], [a], [s], [z], [x], [c], [n] for lowercases and [Shift]+[Right Alt]+these letters for uppercase.
But when i press only [Shift]+[a], atom gives me "Ą" ([RAlt]+[Shift]+[a]) instead of "A".

So i create new json with only lowercases. When I press [Shift]+[RAlt]+[a], Atom gives me lowercase "ą" instead of "Ą".

**Comment by andischerer** [comment]
Multi-modifier bindings are currently not supported yet. 
Seems related to #15.

**Comment by andischerer** [comment]
Multi-Combo bindings are now supported in v1.3.0. 
pl_PL layout is also updated. See #15 for details.
