### ISSUE TITLE
Does not work in Firefox

### ISSUE THREAD

**Issue by screendriver** [andischerer/atom-keyboard-localization#2]
If I open

```
~/.atom/packages/keyboard-localization/keybinding-generator/generate-keybindings.html
```

in Firefox nothing happens on key press. In Chrome everything works fine.

**Comment by papermoon1978** [comment]
Also doesn't work in IE 10. It's only recognizing a keypress event (and not keydown as in Chrome) and it's not generating JSON keybindings. Fine in Chrome

**Comment by andischerer** [comment]
Looks like only Chrome and Safari support `KeyboardEvent.keyIdentifier` which is defined in the old draft of DOM Level 3 Events:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent.keyCode

Atom uses `KeyboardEvent.keyIdentifier` interally to identify which key is pressed. So i suggest using chrome for generating keymaps as atom runs with the same webkit/blink engine.
