### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by screendriver** [andischerer/atom-keyboard-localization#20]
I am using `Atom 0.190.0` on `Mac OS X 10.10.3`. atom-keyboard-localizaton is installed in version 1.2.0 and `de_DE-neo` layout is activated. Today I realized that it is not working anymore. I don't know since when and if this stopped working since an Atom or atom-keyboard-localization update.

**Comment by andischerer** [comment]
Yes could be. In version 1.2.0  made some changes to the modifier behaviour. Which keycode prints the keymap-generator when you press the altgr key ?

**Comment by screendriver** [comment]
I am on a Mac, connected to a Microsoft wireless keyboard and enabled the Neo2 layout. Which key should I press now? :wink:

**Comment by andischerer** [comment]
sorry for the delayed response due to my vacation break. 
Interesting setup by the way ;-) 
Is there any way to use the neo-layout on a standard keyboard ? Looks like i have to install NeoVars driver. My time is very limited at the moment so i cannot say when i can dive into this.
In the meantime you could do a package downgrade to version 1.1.7 and check if it works for you.

```
apm install keyboard-localization@1.1.7
```

**Comment by andischerer** [comment]
could you give a quick example whats not working anymore ?
Single keys, keys in combination with a specific modifier ?

**Comment by screendriver** [comment]
Following Keys are not working anymore `: < > = +`
Everything is like I have not installed atom-keyboard-localization.

**Comment by andischerer** [comment]
Did a downgrade solve this problem ?

**Comment by screendriver** [comment]
Yes, a downgrade solves it :grey_question:

**Comment by screendriver** [comment]
Any news about that?

**Comment by andischerer** [comment]
Probably this weekend i deliver a fix

**Comment by screendriver** [comment]
:+1:

**Comment by andischerer** [comment]
Could you try the latest release and report back if the keys will be working ?

**Comment by screendriver** [comment]
It works :+1:
