### ISSUE TITLE
Not compatible with Neo Layout

### ISSUE THREAD

**Issue by screendriver** [andischerer/atom-keyboard-localization#3]
I am using the German [Neo Layout](http://www.neo-layout.org/). Some Keys like `=` or `<` or `:` does not work in Atom. If I follow your readme and copy the generated JSON into the lib/keymaps directory nothing changed. `<` and `=` and `:` still does not work.
I am using the latest 0.177.0 on Mac OS X Yosemite 10.10.2

**Comment by papermoon1978** [comment]
Maybe this is related to #4 ? Please try renaming your json file to just one character +json (d.json) and adapt your settings.

**Comment by screendriver** [comment]
Awesome! Thank you, it works :+1:

**Comment by andischerer** [comment]
Thanks for reporting. This issue should now be fixed in v1.1.1 so you can rename your keymap file according to your config. 
Important: Please backup your keymap file before updating so it wont get lost.
Are you interested in sharing your keymap file with me ? Please give me a note ;)

**Comment by screendriver** [comment]
I will make a new issue with the pasted keymap in the next couple of days :wink:

**Comment by andischerer** [comment]
Thanks

**Comment by ScreenDriver** [comment]
This is my Neo layout json file (called neo.json)

```javascript
{
    "44": {
        "alted": 34
    },
    "46": {
        "alted": 39
    },
    "65": {
        "alted": 123
    },
    "66": {
        "alted": 43
    },
    "67": {
        "alted": 93
    },
    "68": {
        "alted": 58
    },
    "69": {
        "alted": 125
    },
    "70": {
        "alted": 61
    },
    "71": {
        "alted": 62
    },
    "72": {
        "alted": 60
    },
    "73": {
        "alted": 47
    },
    "74": {
        "alted": 59
    },
    "75": {
        "alted": 33
    },
    "76": {
        "alted": 91
    },
    "78": {
        "alted": 40
    },
    "79": {
        "alted": 42
    },
    "80": {
        "alted": 126
    },
    "81": {
        "alted": 38
    },
    "82": {
        "alted": 41
    },
    "83": {
        "alted": 63
    },
    "84": {
        "alted": 45
    },
    "85": {
        "alted": 92
    },
    "86": {
        "alted": 95
    },
    "87": {
        "alted": 94
    },
    "88": {
        "alted": 8230
    },
    "89": {
        "alted": 64
    },
    "90": {
        "alted": 96
    },
    "223": {
        "alted": 383
    },
    "228": {
        "alted": 124
    },
    "246": {
        "alted": 36
    },
    "252": {
        "alted": 35
    }
}
```

**Comment by screendriver** [comment]
I've made a pull request #5 for this.
