### ISSUE TITLE
fr_FR + MacOS X + Square Brackets bug

### ISSUE THREAD

**Issue by antoinejaussoin** [andischerer/atom-keyboard-localization#36]
Hi,

First, thanks for your plugin, this is exactly what I needed to be able to use Vim mode.

I have an Azerty keyboard (French version, fr_FR), and the Alt + Shift + 5 which should give a square brackets [ actually returns a 5.

To summarise: On an AZERTY keyboard:
- Hitting the "5" key should return an open bracket: (
- Hitting shift + 5 should return 5 (numbers are shifted in azerty)
- Hitting alt + shift + 5 should return an opening square brackets : [

The problem doesn't appear for the closing bracket ], probably because it's not on a "number" key (it's just after the 0 key).

It does appear though "number" keys between 2 and 0.
Oddly enough, if you type Alt + Shift +1, you get the expected ´, and if you follow that directly with a Alt + Shift + 5, you get the square bracket [. Not a very convenient fix though :)

Thanks for your help!!

**Comment by andischerer** [comment]
Could you try the latest version 1.4.7 to see if that helps ?

**Comment by pjean** [comment]
Hi,

First, great thank for that very useful plugin.
I have the 1.4.10 version and Alt(Gr) + Shift + 5 returns { like when I press Alt(Gr) + 5.
Alt(Gr) + Shift + 5 should return [ and not {

Thanks

**Comment by TristanLefebure** [comment]
I have the same issue with 1.4.18 and a french azerty keyboard on Linux (ubuntu), I can't type '('. 
I can't also type =, ] and ". I guess I have a problem with the full top row...

If I disable the package, then it's just fine.

Thanks

**Comment by olivierSemet** [comment]
Same problem 👍

**Comment by franck-tomek** [comment]
Same problem here on a Mac with latest version available: 1.4.18.

**Comment by e2o** [comment]
I'm also having this problem on 1.4.18, alt+shift+5 returns a 5 instead of an opening square bracket.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
