### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by papermoon1978** [andischerer/atom-keyboard-localization#4]
Doesn't work on my system (Windows 7, Atom 179) at all. In the devoloper console it says atom-keymap-compatible: error loading translation table: C:\Users\Username.atom\packages\keyboard-localization\lib\keymaps\d.json but the keymap is defined as 

useKeyboardLayout: 'de_DE'

**Comment by papermoon1978** [comment]
Looks like you're only checking the first character of the filename in key-mapper.coffee. ;-)

if atom.config.get('keyboard-localization.useKeyboardLayout')**[0]**? 
    transTablePath = path.resolve(__dirname, './keymaps/', atom.config.get('keyboard-localization.useKeyboardLayout')**[0]** + '.json') 
    @loadTranslationTable(transTablePath)

**Comment by andischerer** [comment]
yes you are right. I messed around with my local atom config so i dont run into that issue ;)
this should be fixed in v1.1.1

Many thanks for your help ;)
