### ISSUE TITLE
japanese keymap

### ISSUE THREAD

**Issue by nakashk** [andischerer/atom-keyboard-localization#40]
Hi.

i just wrote japanese keymap.
since i'm just started user of github and i don't know how to PR yet, i sent you by this issue ;-)
## i wish this would help japanese atom (especially vim-mode/ex-mode ) users.

{
    "49": {
        "shifted": 33
    },
    "50": {
        "shifted": 34
    },
    "51": {
        "shifted": 35
    },
    "52": {
        "shifted": 36
    },
    "53": {
        "shifted": 37
    },
    "54": {
        "shifted": 38
    },
    "55": {
        "shifted": 39
    },
    "56": {
        "shifted": 40
    },
    "57": {
        "shifted": 41
    },
    "186": {
        "unshifted": 58,
        "shifted": 42
    },
    "187": {
        "unshifted": 59,
        "shifted": 43
    },
    "188": {
        "unshifted": 44,
        "shifted": 60
    },
    "189": {
        "unshifted": 45,
        "shifted": 61
    },
    "191": {
        "unshifted": 47,
        "shifted": 63
    },
    "192": {
        "unshifted": 64,
        "shifted": 96
    },
    "219": {
        "unshifted": 91,
        "shifted": 123
    },
    "220": {
        "unshifted": 92,
        "shifted": 124
    },
    "221": {
        "unshifted": 93,
        "shifted": 125
    },
    "222": {
        "unshifted": 94,
        "shifted": 126
    },
    "226": {
        "unshifted": 92,
        "shifted": 95
    }
}

**Comment by WebFreak001** [comment]
If I get the permission from you I can PR it for you

**Comment by andischerer** [comment]
thx. Will be in the next package version.
