### ISSUE TITLE
Problem with Atom 1.0.3

### ISSUE THREAD

**Issue by warpdesign** [andischerer/atom-keyboard-localization#44]
Atom quietly updated to the latest version today and I noticed that when pressing certain keys, it adds an extra character on the screen.

For example, typing `:` will actually output `:,`

If I disable keyboard-localization it doesn't happen anymore.

I'm using the latest plugin version: 1.4.3, with the french keymap set

**Comment by norbert-berenyi** [comment]
Same problem here. I'm useing the Hungarian layout. Double '-' '_', also dots not working.

**Comment by andischerer** [comment]
duplicate of #43
Please subscribe there.
