### ISSUE TITLE
Does not prevent default keybindings from being fired

### ISSUE THREAD

**Issue by WebFreak001** [andischerer/atom-keyboard-localization#45]
Since today when i press something like `:` on my keyboard it also adds the > which is probably the key that would normally get hit on an english keyboard. This also happens with every key that is not a alphanumeric. `"` -> `"@"` `,` -> `,,` `.` -> `..` etc.

**Comment by andischerer** [comment]
Did you use the latest plugin version ? This should be fixed the lastest version. See #43

**Comment by WebFreak001** [comment]
Oops, thanks its fixed now (just needed to update)
