### ISSUE TITLE
Capital 'Ü' gives '\' (Backspace) on de_DE layout

### ISSUE THREAD

**Issue by schwaerz** [andischerer/atom-keyboard-localization#46]
First of all: Thanks for taking care about this nasty CTRL+ALT vs. Alt Gr issue in atom. Works great!
I've currently installed version **1.4.6** of keyboard-localization package.

I've just some small issue when I try to enter the capital letter 'Ü'.
I just get '\'. But no 'Ü'. Anything else seems to work properly using the latest version.
Tried to get it working using the Keymap-Generator. Unfortunately without success so far.

**Comment by schwaerz** [comment]
That's strange: Once I open the Keymap-Generator and try to enter 'Ü' once into the "Test your generated Key-Mapping" without actually changing anything 'Ü' works. However _IF_ I generated the 'Ü' explicitly it will become '\' again. Generated code remains the same as in de_DE.json.
After clearing the generated Key-Mappings 'Ü' is again there. Hope that helps in fixing the keymap. Tried on my own but I think my js knowledge is not yet good enough...

**Comment by manuel-mauky** [comment]
I have the same problem. :-(

**Comment by schwaerz** [comment]
Looks like there's some special handling implemented for some Chromium bug implemented. Just did some debugging - unfortunately I almost have no know-how in java script, node.js or coffee script at all. Looks like the 'Ü' get replaced by '\' in line `362` in file `.../app-1.0.3/resources/app.asar/node_modules/atom-keymap/lib/helpers.js` while calling function `translateCharCodeForWindowsAndLinuxChromiumBug()`
. Hopefully somebody has some idea.

**Comment by andischerer** [comment]
@schwaerz your on the right spot. I've already noticed this behavior by myself. 
I've already have an idea on fixing it.
I cannot say when i'll be able to start working on this, my time is currently limited at the moment.

**Comment by schwaerz** [comment]
At least I found a workaround on my machine - please check my pull request whether it has some side effects or needs testing.

**Comment by andischerer** [comment]
should be fixed in v1.4.7

**Comment by schwaerz** [comment]
Thanks. Works for me.
