### ISSUE TITLE
Breaks Ctrl+# (comment)

### ISSUE THREAD

**Issue by ghost** [andischerer/atom-keyboard-localization#47]
With this package with de_DE layout the Ctrl+# command does not work anymore... :cry: 

Version 1.4.6
Atom 1.0.3
Windows 7

**Comment by bendkt** [comment]
I do experience this issue, too. 
Version 1.4.6
Atom 1.0.4
Windows 8.1

**Comment by andischerer** [comment]
should be fixed in v1.4.7

**Comment by rugk** [comment]
It's fixed, yes.
