### ISSUE TITLE
Key presses of special characters are duplicated

### ISSUE THREAD

**Issue by jpmn** [andischerer/atom-keyboard-localization#49]
I use the fr_CA keyboard layout and whenever I press keys such as "$", ".", "_", it appends a duplicate character like "$$", "..", "__" which is very annoying.

The behavior stops when I disable the package, but it also brings back the keyboard issues I had:
alt_car + [ and alt_car + ] expands and collapses rows instead of printing [ and ].

Atom 1.0.3
Package 1.4.6
Windows 10

**Comment by heinrich-S** [comment]
Same problem here with

Atom 1.0.4
Package 1.4.6 and one version before, i think 1.4.4
Windows 7

**Comment by andischerer** [comment]
should be fixed in v1.4.7

**Comment by jpmn** [comment]
I can confirm that it works in version 1.4.7. Thank you!

**Comment by andischerer** [comment]
thx
