### ISSUE TITLE
Wrong characters on Mac OS X

### ISSUE THREAD

**Issue by slhck** [andischerer/atom-keyboard-localization#50]
Using version 1.4.6 on Atom 1.0.3 on OS X 10.10, German (QWERTZ) keyboard layout.

When I type `Shift-Alt-8` and `Shift-Alt-9` I would expect `{` and `}`, but I get `[` and `]`.

When I type `Alt-7` I would expect `|`, but I get `{`.

It seems like the default US keys are taken. There are probably more of these.

I think that it used to work; not sure which update broke it – maybe it was Atom 1.0.3 and in the "aftermath" around that release, OS X was not tested? Or perhaps I should disable it altogether on OS X?

**Comment by andischerer** [comment]
I've done some major refactoring in handling keystrokes. Unfortunately I have no darwin machine to test to.
Could you try the latest version 1.4.7 ?

**Comment by slhck** [comment]
Unfortunately it doesn't work. Latest Atom 1.0.5 and your version 1.4.7. The symptoms are the same as described above.

If you can give me some instructions to test something, I can try that. However, keep in mind that I have literally no experience whatsoever with Node.js, Atom's internals, or any of that stuff.

**Comment by slhck** [comment]
It still does not work with v1.4.10 on Atom 1.2.9.  The symptoms are exactly as described initially.

When I disable the package, I get the correct results, by the way. So maybe it simply needs to be bypassed for OS X, or is it more complicated than that?

**Comment by mrwest808** [comment]
Same problem on a swedish keyboard with Atom v1.5.4 and v1.4.15 of this package.

Since I enter a `{` character with `Shift-Alt-8` (2 modifier keys), is it even possible to target that in a custom keymap file?

``` js
"56": {
  "shifted": 40, // resolves to `(` which is correct
  "alted": 91, // resolves to `[` which is correct
  // how would I add something that is both "shifted" and "alted"?
  "shifted+alted": 123
},
```

I'm not even sure this would work, my problem is trying to get `vim-mode` to recognize curly brackets in combination with operators, like `c i {` etc.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
