### ISSUE TITLE
commenting refuses to work after switching to fr_BE keyboard layout

### ISSUE THREAD

**Issue by vanhumbeecka** [andischerer/atom-keyboard-localization#52]
commenting stops working, both for standard key-combo `ctrl+/` as for the emmet shortcut `ctrl+shift+/` when selecting the fr_BE keyboard layout.

**Comment by tainmar** [comment]
Same here with fr_FR

**Comment by tainmar** [comment]
Any news on that issue ? Thanks.

**Comment by vanhumbeecka** [comment]
Tried again today. `ctr+/` still does not work, but `ctrl+shift+/` (emmet package) does work in a html file when a piece of code is selected. 

So still not fixed..

**Comment by Oli4242** [comment]
Same issue with fr_FR (actually it works with the `/` key from the numpad)

I haven't taken the time to understand how the package works but I've fixed this by deleting the following lines from `lib/keymaps/fr_FR.json`:

``` json
"191": {
      "unshifted": 58,
      "shifted": 47
    },
```

Atom needs to be restarted (or disable / enable the package so it reloads the keymaps).

**Comment by cyrilchapon** [comment]
@Oli4242 thanks for the numpad workaround though.

**Comment by cyrilchapon** [comment]
A year later => any new on that issue ?

**Comment by andischerer** [comment]
Things are moving.
See #146

**Comment by cyrilchapon** [comment]
If it can help : as for myself (just fresh out-of-the-box settings along with keyboard-localization FR_fr), the package "spellchecker" was overriding the default "ctrl + :" bound to toggle comment. I just disabled spellchecker and it works back, with keyboard-localization bindings without even editing keymap.cson.

I'd recommend using keybind resolver to see what's happening for you guys. This is what pointed me in the right direction.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)

**Comment by cyrilchapon** [comment]
Thanks for pointing this out @andischerer
