### ISSUE TITLE
de (QWERTZ) layout not working after upgrading to 1.0.7

### ISSUE THREAD

**Issue by TomasLongo** [andischerer/atom-keyboard-localization#54]
After upgrading to 1.0.7 Atom shows up 2 chars on a keypress, beeing the characters from the german (as the german layout is what I set) and US-layout. For example pressing shift+8 results in (*

OS: Kubuntu 14.10 Kernel-Version 3.16.0

**Comment by andischerer** [comment]
are you using the latest package version ?

Tomas notifications@github.com schrieb am Do., 20. Aug. 2015 21:31:
