### ISSUE TITLE
tested: Slovenian (sl_SL) 

### ISSUE THREAD

**Issue by erikusaj** [andischerer/atom-keyboard-localization#55]
Tested on Slovenian (sl_SL): 

Works OK. For 
AltGr+Q = \ 
AltGr+W = |
AltGr+E = €
AltGr+W = ÷
AltGr+E = ×
AltGr+F = [
AltGr+G = ]
AltGr+K = ł
AltGr+L = Ł
AltGr+V = @
AltGr+B = {
AltGr+N = }
AltGr+M = §

**Good enough for development.**

Minor issues with:
1)
No input for:
AltGr+Ž = ¤

2)
Composing characters on AltGr + 1..9 , AltGr+' , AltGr++ 
Composing character is entered and additional composed character.

For example composing U with umlaut (ü):
1. type AltGr+ ' 
2. type u
text in editor: ¨ü
expected text: ü
Workaround: delete extra character.

Please advise with file(s) do I need to update for fixing 1) and 2).

**Comment by andischerer** [comment]
Hi,

1) I currently dont see any fix, because keycode 164(U+00A4) gets internally rewritten from atom-keymap to alt key [see here](https://github.com/atom/atom-keymap/blob/master/src/helpers.coffee#L19)

2) should be fixed in the next version

Thanks for testing :+1:
