### ISSUE TITLE
Pipe not working on Xubuntu (German layout)

### ISSUE THREAD

**Issue by JAAdrian** [andischerer/atom-keyboard-localization#56]
Hi,
since the new version 1.6.9 came out, I can't use the pipe symbol by typing `alt-gr + <` in the German layout.
Instead the combination produces a caret `^`.

atom-keyboard-localization v1.6.9
Atom 1.0.7
Xubuntu 15.04

**Comment by andischerer** [comment]
will be fixed in the next version
