### ISSUE TITLE
Key-Mappings not shown

### ISSUE THREAD

**Issue by AlexRRR** [andischerer/atom-keyboard-localization#57]
Hi there, I am currently looking for a workaround so I can use atom and my Swiss German keyboard layout, but I cannot get any Key-Mappings generated as in your example

![Key_mappings](http://zippy.gfycat.com/UnripeBestChanticleer.gif)

Atom 1.0.9
Mac OS X 10.10.5
Keyboard-Localization: 1.4.8

**Comment by ptrblgh** [comment]
:+1:

**Comment by renestalder** [comment]
Same problem. I have no idea how this generator works or it may not work anyway. Also need the Swiss german mapping.

**Comment by AlexRRR** [comment]
@renestalder you might want to try my pull request #59 , for me (Mac OS X) Only the `@` was missing. Also I see there is already a pull request for FR_CH keyboard.

**Comment by renestalder** [comment]
Well, could get a work around with adding something like this to my keymap.cson in atom, but feels hacky:

``` cson
'atom-workspace atom-text-editor:not([mini])':
  'alt-g': 'native!'
```
