### ISSUE TITLE
CTRL+/

### ISSUE THREAD

**Issue by Stanzilla** [andischerer/atom-keyboard-localization#63]
On a German keyboard it's kinda impossible to press <kbd>CTRL</kbd>+<kbd>/</kbd> at the same time, should it be mapped to something like <kbd>CTRL</kbd>+<kbd>7</kbd> instead? Or does it work when you press <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>7</kbd>?

**Comment by andischerer** [comment]
Hi, <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>7</kbd> resolves to <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>/</kbd>.
I think i would remap the keybinding to <kbd>CTRL</kbd>+<kbd>7</kbd>
