### ISSUE TITLE
stop default keybindings

### ISSUE THREAD

**Issue by papermoon1978** [andischerer/atom-keyboard-localization#7]
default German keyboard layout,  Windows 7.

Without using your package, when typing @, this calls autoflow:reflow-selection and when typing \ this calls editor:fold-current-row.

Now using your package I'm finally able to type @ and \ as normal characters but the atom commands are also executed. So when typing @ it will show the character in the editor but also reflow the selection and the same goes for \. I see the \ in the editor but the rows are folded together. Is there any chance to build into the package that only the specific character is passed to the editor without executing assigned commands?

**Comment by andischerer** [comment]
yes, i have noticed this behaviour already by myselve. I have to dive deeper into this issue. 
As workaround add the following lines to your atom keymap.cson:

```
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-[': 'unset!'
```

**Comment by papermoon1978** [comment]
Doesn't work unfortunately. I added 

```
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-[': 'unset!'

'.platform-win32 atom-text-editor, .platform-linux atom-text-editor':
  'ctrl-alt-q': 'unset!'
```

and the keybinding list shows them as unset, but still the character is shown in the editor and the command is executed as well

![atom](https://cloud.githubusercontent.com/assets/4062007/6389649/264a1de6-bda6-11e4-8588-93a4f593f84f.png)

**Comment by andischerer** [comment]
hmm... could you add the following code in your atom init script(init.coffee) and test again please ?

```
atom.keymap.keyBindings = atom.keymap.keyBindings.filter((binding, i) ->
  ['ctrl-alt-['].indexOf(binding.keystrokes) == -1
)
```

**Comment by papermoon1978** [comment]
works fine. Thanks :-)

**Comment by andischerer** [comment]
This issue should be fixed in the brand new v1.1.4. Dont forget to remove the workaround fix in your init.coffee.

**Comment by papermoon1978** [comment]
Yes, works fine :-) Thanks

**Comment by sergiopvilar** [comment]
Awesome, this solved my problem too. Thanks!

**Comment by OmegaExtern** [comment]
Doesn't work for me (outdated?). Cannot read property 'keyBindings' of undefined.

**Comment by sergiopvilar** [comment]
@OmegaExtern use `keymaps` instead of `keymap`.

**Comment by tzs007** [comment]
it didn't work... nothing happened

**Comment by OmegaExtern** [comment]
@tzs007 I have solved my case (some time ago), similar to this, give it a try:

```
".platform-win32 atom-text-editor, .platform-linux atom-text-editor":
  "ctrl-alt-q": "unset!"
"atom-workspace atom-text-editor:not([mini])":
  "alt-ctrl-f": "unset!"
  "ctrl-alt-[": "unset!"
  "ctrl-alt-]": "unset!"
  "ctrl-alt-{": "unset!"
  "ctrl-alt-}": "unset!"
  "ctrl-alt-f": "unset!"
"atom-text-editor":
  "ctrl-alt-f": "unset!"
  "alt-f": "unset!"
  "alt-ctrl-f": "unset!"
  "alt-F": "unset!"
  "alt-ctrl-F": "unset!"
  "alt-b": "unset!"
  "alt-ctrl-b": "unset!"
  "alt-B": "unset!"
  "alt-ctrl-B": "unset!"
  "alt-h": "unset!"
  "alt-ctrl-h": "unset!"
  "alt-d": "unset!"
  "alt-ctrl-d": "unset!"
  "ctrl-alt-b": "unset!"
".platform-win32, .platform-linux":
  "ctrl-alt-f": "unset!"
"atom-workspace atom-text-editor:not([mini])":
  "alt-ctrl-f": "unset!"
  "ctrl-alt-[": "unset!"
".platform-win32 atom-text-editor, .platform-linux atom-text-editor":
  "ctrl-alt-q": "unset!"
".platform-win32, .platform-linux":
  "ctrl-alt-f": "unset!"
"atom-text-editor":
  "alt-ctrl-f": "unset!"
  "alt-ctrl-F": "unset!"
  "alt-ctrl-b": "unset!"
  "alt-ctrl-B": "unset!"
```

This fixed it completely for my keyboard..
Unsets actions from [(Ctrl+Alt)/Alt Gr]+Q "\", [(Ctrl+Alt)/Alt Gr]+F "[" and [(Ctrl+Alt)/Alt Gr]+B "{".
I have lost a week on this until I got it. Hopefully this helped you.

**Comment by tzs007** [comment]
@OmegaExtern whoa! u da man!:D thanks! it works
