### ISSUE TITLE
Symbols needing AltGr don't show up anymore

### ISSUE THREAD

**Issue by dogoepp** [andischerer/atom-keyboard-localization#76]
Hi and thanks for your package !

I met a problem when using it with my french keyboard: the characters  usually available by pressing AltGr + other key no longer work in Atom. It comes from that plugin since whenever I disable it, the keys work again.

**Comment by andischerer** [comment]
Hi, could you give a quick example which keybindings wont produce characters anymore ?

**Comment by dogoepp** [comment]
Hi Andreas,

For instance AltGR + `"` should give`#` and AltGR + `(` should give '['.

**Comment by NKjoep** [comment]
Hi, I have the same issue, but with the locale it_IT.

| key combo | expected behavior | wrong result |
| --- | --- | --- |
| altgr - shift - è | { | é |
| altgr- shift - + | } | * |

**Comment by Gabriele-Tomberli** [comment]
Can confirm @NKjoep issues with the Italian layout.
Fixed it with this custom keymap:

{
    "186": {
        "alted": 91,
        "altshifted": 123
    },
    "187": {
        "alted": 93,
        "altshifted": 125
    }
}

**Comment by IceOnFire** [comment]
I created pull request https://github.com/andischerer/atom-keyboard-localization/pull/91 to fix this problem, meanwhile Zelgadis87's hack works gr8! ;)

**Comment by dogoepp** [comment]
Thanks !
