### ISSUE TITLE
Portuguese keyboard has duplicate keyCodes

### ISSUE THREAD

**Issue by pedrocarmo** [andischerer/atom-keyboard-localization#77]
The portuguese keyboard is reading the same keycode (220) for the key with  `\` `|` and the one with `<` `>`

This makes it impossible to bind them correctly, I get either one or the other working.

**Comment by andischerer** [comment]
See #19.

It worked for some users when they removed the remap of keycode 220 in their keymap-json-file to be able to write both keycode 220 bindings.

**Comment by pedrocarmo** [comment]
This worked, thanks!

(Not sure if I should close it or it's still an issue)

**Comment by andischerer** [comment]
No Problem leave it open. I'll need to fix the portuguese keyboard layout for keycode 220 for the next version.
