### ISSUE TITLE
'KeyboardEvent.keyLocation' is deprecated

### ISSUE THREAD

**Issue by gjmveloso** [andischerer/atom-keyboard-localization#78]
Atom latest version (1.0.19) is throwing deprecated messages on keyboard-localization package:

> .atom\packages\keyboard-localization\lib\modifier-state-handler.coffee:143 'KeyboardEvent.keyLocation' is deprecated. Please use 'KeyboardEvent.location' instead.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
