### ISSUE TITLE
French version doesn't seem to work

### ISSUE THREAD

**Issue by warpdesign** [andischerer/atom-keyboard-localization#8]
Hi, just tested the latest french with a French keymap and it doesn't seem to work:

Pressing `altgr + )` stills acts as code folding shortcut (which is bound to `ctrl+alt+)`.

The character I wanted is correctly printed though.

**Comment by andischerer** [comment]
#7

**Comment by andischerer** [comment]
I am currently working on that. It seems to be the same behaviour like Issue #7. The default shortcut command is not prevented from beeing fired event if the right char is printed. Which Key does the keybinding resolver resolve?
In the meantime you could use the following workaround for your init.coffee:

```
atom.keymap.keyBindings = atom.keymap.keyBindings.filter((binding, i) ->
  ['ctrl-alt-)'].indexOf(binding.keystrokes) == -1
)
```

**Comment by warpdesign** [comment]
I see.
I added the above line but it didn't work (I restarted Atom).

**Comment by andischerer** [comment]
Could you try the new v1.1.4. The default keybindings should not fire anymore.
