### ISSUE TITLE
es_LA layout: AltGr plus "{" or "}" with strange behaviour 

### ISSUE THREAD

**Issue by jecastro1** [andischerer/atom-keyboard-localization#84]
Hello, first thank you for this package. I have an issue with es_LA keyboard layout:
##### Situation

When I press `AltGr` + `}` and then `SPACE` I expect to get two **`** chars, but I get an `}` and then (when I press the `SPACE` key) two **`** chars.

I get a similar result when I try to get the `^` char with `AltGr` + `{` and then `SPACE`.
##### When it doesn't occur

This issue dissapears if I open the Keymap-Generator at least once each time I restart Atom.

Thanks!

**P.S.** I use Windows 8.1

**Comment by andischerer** [comment]
Fix will be :ship: in the next release
