### ISSUE TITLE
add support for hr_HR

### ISSUE THREAD

**Issue by gour** [andischerer/atom-keyboard-localization#85]
Can you add support for hr_HR (Croatian) keyboard which is identical to sl_SL keymap?

Well, keyboard layout is the same, but, being quite noob with Atom, I still have to check whether sl_SL is complete since I have issues with it like #80.

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
