### ISSUE TITLE
[, ] and \ (Alt-Gr mappings) missing in fr_CH

### ISSUE THREAD

**Issue by jruffin** [andischerer/atom-keyboard-localization#87]
The fr_CH layout seems to be missing three mappings: [ (AltGr-è), ] (AltGr-") and \ (AltGr-<). The following custom mappings fix it:

```
{
    "186": {
        "alted": 91
    },
    "192": {
        "alted": 93
    },
    "226": {
        "alted": 92
    }
}
```

Everything else works flawlessly already, so thanks for the package!

**Comment by jruffin** [comment]
Something is amiss - the problem might come from me using several keyboard layouts at once (de_DE and fr_CH). It might be that issue I was having was because of me using de_DE in the settings with fr_CH set under windows, though the plugin works even less well when set to fr_CH.

Unless somebody has the same issue, I wouldn't bother anymore.

**Comment by luxigo** [comment]
Hi !

I opened a related issue #108
