### ISSUE TITLE
Preferences shortcut (Ctrl+comma) doesn't work with es_ES keyboard layout

### ISSUE THREAD

**Issue by ricpelo** [andischerer/atom-keyboard-localization#93]
Using Atom 1.3.0 and keyboard-localization 1.4.11. The 'Preferences' shortcut (Ctrl+comma) doesn't work with 'es_ES' keyboard layout.

**Comment by andischerer** [comment]
works for me, what does the keybinding resolver say ? 
Could be conflict in keybindings from an other package.

**Comment by ricpelo** [comment]
Thanks for the reply. How can I see the keybinding resolver?

**Comment by andischerer** [comment]
Menu > Package > Keybinding Resolver > Toggle or press <kbd>CTRL + .</kbd>

**Comment by ricpelo** [comment]
Great, this is what I get:

```
Key binding resolver: ,

vim-mode:repeat-find-reverse  atom-text-editor:vim-mode:not(.insert-mode)  /home/ricardo/.atom/packages/vim-mode/keymaps/vim-mode.cson
```

It's worth noting that 'Key binding resolver: ' shows ',' instead of 'Ctrl ,'.

**Comment by andischerer** [comment]
Does it work when you switch vim into insert-mode ?
In command mode it doesnt work for me either.

**Comment by ricpelo** [comment]
Oh, it works when in insert-mode! O_o. How embarrasing... Didn't notice that earlier, sorry!

**Comment by andischerer** [comment]
No Problem
