### ISSUE TITLE
de_CH

### ISSUE THREAD

**Issue by jonnitto** [andischerer/atom-keyboard-localization#96]
The keymap for de_CH isn't correct. For example: If I want to type `{`, I get `¢`...

**Comment by floriangaechter** [comment]
I had the same problem. Actually, I just needed the package to get the <kbd>@</kbd> key working on the swiss german keyboard but I realized you can do the same thing by reassigning the <kbd>alt</kbd> <kbd>g</kbd> keybinding in your `keymap.cson` file like this:

```
'atom-workspace':
    'alt-g': 'native!'
```

Keep in mind though, you'll lose some GitHub specific shortcuts if you do it this way (have a look at the keybindings in the settings).

**Comment by RogerGMartins** [comment]
on fr_CH there are some problems as well.
} prints $, tried to fix it with the keymap generator, but even there the event captured is $ (even with altgr pressed)

edit: tried some more with the keymap generator, i noticed if i had pressed for instance '$' and then tried to do the '}' (altGr+$), it wouldnt work
but doing it the other way arround the keymap generator was able to pick up both keycodes

i think this the same as #141

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
