### ISSUE TITLE
fr_ca: { output as \

### ISSUE THREAD

**Issue by sebastien** [andischerer/atom-keyboard-localization#98]
The correct value on my keyboard is 

```
{
    "222": {
        "alted": 123
    }
}
```

**Comment by jpmn** [comment]
The correct value on my keyboard is

```
{
    "222": {
        "alted": 92
    }
}
```

Since this commit, it keeps printing `{` instead of `\` when pressing `altgr + ~`. I tried two different keyboards plus my laptop's and it returns the same keycodes.

**Comment by sebastien** [comment]
Oops, sorry about that. I never managed to get Atom to work properly in all cases, but I'm using an unusual keyboard (Truly Ergonomic Kbd).

**Comment by jpmn** [comment]
No harm done, I just thought I would tell the author!

**Comment by jpmn** [comment]
@andischerer Do you think to be able to undo this commit (https://github.com/andischerer/atom-keyboard-localization/commit/414576c779773fc92a3c51ba3de57e304e7f2459)? Thank you!
